//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Veipshop.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VapeEntities : DbContext
    {
        public VapeEntities()
            : base("name=VapeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Basket> Basket { get; set; }
        public virtual DbSet<Brand> Brand { get; set; }
        public virtual DbSet<Country> Country { get; set; }
        public virtual DbSet<Manufacturer> Manufacturer { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<Pod> Pod { get; set; }
        public virtual DbSet<Products> Products { get; set; }
        public virtual DbSet<Section> Section { get; set; }
        public virtual DbSet<Tobacco_heating_systems> Tobacco_heating_systems { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Vapes> Vapes { get; set; }
        public virtual DbSet<Vaping_liquid> Vaping_liquid { get; set; }
    }
}
