//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Veipshop.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vaping_liquid
    {
        public int vaping_liquid_id { get; set; }
        public Nullable<int> product_id { get; set; }
        public string taste { get; set; }
        public string volume { get; set; }
        public string strong { get; set; }
    
        public virtual Products Products { get; set; }
    }
}
